# Generated by Django 4.2.5 on 2023-10-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_hotel_room_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenities",
            name="has_ac",
            field=models.BooleanField(default=False),
        ),
    ]
