# Generated by Django 4.2.5 on 2023-10-25 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0004_amenities_has_ac"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("service_name", models.CharField(max_length=50)),
                ("service_Price", models.IntegerField(default=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="hotel",
            options={"ordering": ["hotel_price"]},
        ),
        migrations.CreateModel(
            name="Service_bookings",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("person_count", models.IntegerField(default=2)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_booking",
                        to="home.services",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ser_booking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("person_count", models.IntegerField(default=2)),
                ("Service_charges", models.IntegerField(default=1000)),
                ("Rent_charges", models.IntegerField(default=1000)),
                ("Total_charges", models.IntegerField(default=2000)),
                (
                    "room_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.hotelbooking",
                    ),
                ),
                (
                    "service_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.service_bookings",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
