# Generated by Django 4.2.5 on 2023-10-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_services_alter_hotel_options_service_bookings_bill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="person_count",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="room_booking",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="service_booking",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="user",
        ),
        migrations.RemoveField(
            model_name="service_bookings",
            name="user",
        ),
        migrations.AddField(
            model_name="bill",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_booking",
                to="home.hotelbooking",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="isPaid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotelbooking",
            name="booking_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="service_bookings",
            name="deli_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="service_bookings",
            name="hotel_booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_booking",
                to="home.hotelbooking",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="service_desc",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="service_bookings",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="home.services",
            ),
        ),
    ]
